# Generated by Django 5.1.5 on 2025-02-04 15:56

import django.core.validators
import gestion.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10), gestion.validadores.validacion_numeros])),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(blank=True, max_length=50, verbose_name='Apellidos dd')),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
                ('cargo', models.CharField(choices=[('Gerente', 'Gerente'), ('Vendedor', 'Vendedor'), ('Cajero', 'Cajero'), ('Contador', 'Contador'), ('Auxiliar', 'Auxiliar'), ('Gerente de almacen', 'Gerente de almacen')], max_length=50)),
            ],
            options={
                'verbose_name': 'Empleado xx',
                'verbose_name_plural': 'Empleados yy',
                'db_table': 'Empleados',
            },
        ),
    ]
